---
version: 2
jobs:
  build:
    working_directory: ~/ansible-rundeck
    docker:
      - image: circleci/python:3.7.2
    steps:
      - checkout
      - run: sudo chown -R circleci:circleci /usr/local/bin
      - run: sudo chown -R circleci:circleci /usr/local/lib/python3.7/site-packages
      - run:
          command: |
            sudo pip3 install molecule docker-py
      - run:
          command: |
            molecule --debug test
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: test-results
          destination: tr1
